language: shell

notifications:
  slack: naturalis:ezcm1O2U6hlcJ5tWsWrBAqRF

services:
  - docker

script:
 - REV=$(git rev-parse --short HEAD)
 - ( cd docker ; docker build -t naturalis/nba-percolator:$TRAVIS_BRANCH-$REV . )

after_success:
  - docker login -u naturalistravisbuilder -p $DOCKER_PASS
  - docker push naturalis/nba-percolator:$TRAVIS_BRANCH-$REV
  - docker logout

